format = """
[](162)\
$username\
[](bg:124 fg:162)\
$directory\
[](fg:124 bg:167)\
$git_branch\
$git_status\
[](fg:167 bg:123)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:123 bg:73)\
$docker_context\
[](fg:73 bg:81)\
$time\
[ ](fg:81)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:162"
style_root = "bg:162"
format = '[$user ]($style)'

[directory]
style = "bg:124"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:123"
format = '[[ $symbol ($version) ](bg:123)]($style)'

[docker_context]
symbol = " "
style = "bg:73"
format = '[[ $symbol $context ](bg:73)]($style) $path'

[elixir]
symbol = " "
style = "bg:123"
format = '[[ $symbol ($version) ](bg:123)]($style)'

[elm]
symbol = " "
style = "bg:123"
format = '[[ $symbol ($version) ](bg:123)]($style)'

[git_branch]
symbol = ""
style = "bg:167"
format = '[[ $symbol $branch ](bg:167)]($style)'

[git_status]
style = "bg:167"
format = '[[($all_status$ahead_behind )](bg:167)]($style)'

[golang]
symbol = " "
style = "bg:123"
format = '[[ $symbol ($version) ](bg:123)]($style)'

[haskell]
symbol = " "
style = "bg:123"
format = '[[ $symbol ($version) ](bg:123)]($style)'

[java]
symbol = " "
style = "bg:123"
format = '[[ $symbol ($version) ](bg:123)]($style)'

[julia]
symbol = " "
style = "bg:123"
format = '[[ $symbol ($version) ](bg:123)]($style)'

[nodejs]
symbol = ""
style = "bg:123"
format = '[[ $symbol ($version) ](bg:123)]($style)'

[nim]
symbol = " "
style = "bg:123"
format = '[[ $symbol ($version) ](bg:123)]($style)'

[rust]
symbol = ""
style = "bg:123"
format = '[[ $symbol ($version) ](bg:123)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:81"
format = '[[ ♥ $time ](bg:81)]($style)'
